// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCshf2L0AHj_t-6yUTDxgiNBPIa8zEjJKI',
    appId: '1:877675965690:web:73723d5523542c094ded43',
    messagingSenderId: '877675965690',
    projectId: 'qualitysphere-simple',
    authDomain: 'qualitysphere-simple.firebaseapp.com',
    storageBucket: 'qualitysphere-simple.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjVHQ0pFm-BixWzxJxRh6YajG-CuJv9gQ',
    appId: '1:877675965690:android:bdeedf4e96bbbf254ded43',
    messagingSenderId: '877675965690',
    projectId: 'qualitysphere-simple',
    storageBucket: 'qualitysphere-simple.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAhpCpftT5IpoeawSVW29pyahHsTiTmLo',
    appId: '1:877675965690:ios:965cf6c88a3bb03d4ded43',
    messagingSenderId: '877675965690',
    projectId: 'qualitysphere-simple',
    storageBucket: 'qualitysphere-simple.firebasestorage.app',
    iosBundleId: 'com.example.qualityaphereSimple',
  );

}